spring:
  config:
    import: "file:../.env[.properties]"
  application:
    name: kotlin-micro-order
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

