spring:
  config:
    import: "file:../.env[.properties]"
  application:
    name: kotlin-micro-order
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: orders-service
application:
  kafka:
      topic: create-orders-topic
server:
  port: 8070

